# Generated by Django 3.2.7 on 2023-04-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('note_name', models.CharField(max_length=50)),
                ('note_text', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('fav', models.CharField(default='F', max_length=5)),
            ],
        ),
    ]
